#![allow(clippy::items_after_test_module)]
//! # Physical Constants of the GENESIS Cognitive Core
//!
//! Every constant defined here is a **physical law** of the system.
//! No implementation may substitute, approximate, or override these values
//! without an explicit architectural exception signed by the Principal Architect.
//!
//! AX-ID: AXIOMA-001 (Clifford substrate), AXIOMA-002 (Minkowski geometry)

use core::num::NonZeroUsize;

// ============================================================================
// COGNITIVE PLANCK CONSTANT
// ============================================================================

/// Minimum energy threshold below which information is treated as thermal
/// noise and discarded without computation.
///
/// Used as the Cauchy-Schwarz gating threshold in `sparse_geometric_product`.
/// Any `top_k_magnitude` product below this value causes the function to
/// return `Option::None` immediately, saving CPU cycles.
///
/// AX-ID: AXIOMA-001 — Substrate Geometric Fundamental
pub const COGNITIVE_PLANCK_CONSTANT: f64 = 1e-12;

// ============================================================================
// MINKOWSKI METRIC SIGNATURE (1,3)
// ============================================================================

/// Diagonal of the Minkowski metric tensor `η_μν` with signature (+, −, −, −).
///
/// Index mapping:
/// - `[0]` → e₀ (time-like basis):   η₀₀ = +1.0
/// - `[1]` → e₁ (space-like basis):  η₁₁ = −1.0
/// - `[2]` → e₂ (space-like basis):  η₂₂ = −1.0
/// - `[3]` → e₃ (space-like basis):  η₃₃ = −1.0
///
/// **Invariant:** This signature MUST be preserved across every internal
/// transformation. Any automorphism of the Clifford algebra that alters this
/// signature is a violation of AXIOMA-001.
///
/// AX-ID: AXIOMA-001, AXIOMA-002
pub const MINKOWSKI_SIGNATURE: [f64; 4] = [1.0, -1.0, -1.0, -1.0];

// ============================================================================
// SPATIAL BASIS MASK
// ============================================================================

/// Bitmask identifying the three spatial basis indices {e₁, e₂, e₃} within
/// a packed Clifford blade index representation.
///
/// In the blade index encoding used by `genesis-math`, the k-th bit represents
/// the presence of basis vector `e_k`. Bits 1, 2, 3 correspond to spatial bases.
///
/// Used in `compute_clifford_sign` to count spatial contractions (`N_s`) for
/// the Minkowski correction factor (`ENGINEERING_BLUEPRINT` §2).
///
/// AX-ID: AXIOMA-001
pub const SPATIAL_BASIS_MASK: usize = 0b1110; // bits 1, 2, 3

// ============================================================================
// MAXIMUM CLIFFORD GRADE AND BASIS SIZE
// ============================================================================

/// Maximum grade in G(1,3): grades 0 (scalar) through 4 (pseudoscalar).
///
/// G(1,3) is generated by 4 basis vectors {e₀, e₁, e₂, e₃}, yielding
/// grades 0..=4. Total blade count = 2^4 = 16.
///
/// AX-ID: AXIOMA-001
pub const MAX_CLIFFORD_GRADE: usize = 4;

/// Total number of basis blades in G(1,3): 2^`MAX_CLIFFORD_GRADE` = 16.
///
/// **Single source of truth:** Derived at compile time from `MAX_CLIFFORD_GRADE`
/// via `1 << MAX_CLIFFORD_GRADE`. Any change to the algebra dimensionality
/// propagates here automatically without risk of silent divergence.
/// A literal `16` is architecturally forbidden.
///
/// AX-ID: AXIOMA-001
pub const CLIFFORD_BASIS_SIZE: usize = 1 << MAX_CLIFFORD_GRADE;

// ============================================================================
// SATIATION PARAMETERS
// ============================================================================

/// Default epsilon for the Fisher metric stability gate.
///
/// When `|∂g_ij(θ)/∂t| < FISHER_SATIATION_EPSILON` for
/// `FISHER_SATIATION_WINDOW` consecutive iterations, the system declares
/// domain satiation and blocks further ingestion in that branch.
///
/// AX-ID: AXIOMA-008 — Satiation and Self-Evaluation by Fisher Stability
pub const FISHER_SATIATION_EPSILON: f64 = 1e-6;

/// Default sliding window (in iterations) for the Fisher satiation gate.
///
/// `NonZeroUsize` guarantees at compile time that division by this value
/// in `FisherGate::delta_g()` is safe. Using it as loop count is
/// always meaningful (the window never has zero iterations).
///
/// The gate fires when the Fisher metric gradient stays below
/// `FISHER_SATIATION_EPSILON` for this many consecutive iterations.
///
/// Access the raw value with `.get()`.
///
/// AX-ID: AXIOMA-008 — Satiation and Self-Evaluation by Fisher Stability
// SAFETY: 50 is a non-zero literal. NonZeroUsize::new(50).unwrap() is the const-safe
// equivalent but Option::unwrap() is not yet stable as a const fn on our MSRV (Rust 1.75).
// When MSRV >= 1.83, replace with: NonZeroUsize::new(50).unwrap()
// SAFETY: 50 is non-zero; new_unchecked avoids const-unstable Option::unwrap on MSRV 1.75.
#[allow(clippy::useless_nonzero_new_unchecked)]
pub const FISHER_SATIATION_WINDOW: NonZeroUsize = unsafe { NonZeroUsize::new_unchecked(50) };

// ============================================================================
// CRITICALITY PARAMETERS
// ============================================================================

/// Lower bound of the acceptable power-law exponent τ for the avalanche
/// size distribution P(S) ∝ S^{−τ} at the self-organised critical point.
///
/// AX-ID: AXIOMA-005 — Self-Organised Criticality
pub const SOC_TAU_MIN: f64 = 1.5;

/// Upper bound of the acceptable power-law exponent τ for the avalanche
/// size distribution P(S) ∝ S^{−τ} at the self-organised critical point.
///
/// AX-ID: AXIOMA-005 — Self-Organised Criticality
pub const SOC_TAU_MAX: f64 = 2.5;

// ============================================================================
// SYNCHRONY THRESHOLD
// ============================================================================

/// Kuramoto order parameter threshold r above which a grade-level phase
/// collapse (Lindblad measurement) is triggered.
///
/// The order parameter r = |Σ e^{iφ}| / N ∈ [0, 1].
/// When r > `SYNCHRONY_COLLAPSE_THRESHOLD`, `execute_partial_collapse` fires.
///
/// AX-ID: AXIOMA-006 — Emergence by Phase Synchronisation
pub const SYNCHRONY_COLLAPSE_THRESHOLD: f64 = 0.85;

// ============================================================================
// WORMHOLE / MYELINATION
// ============================================================================

/// Ollivier-Ricci curvature threshold for wormhole collapse (myelination).
///
/// A highly negative curvature indicates strong semantic attraction between
/// two concept clusters.
///
/// AX-ID: AXIOMA-015 — Myelination by Coupled Ricci Flow
pub const WORMHOLE_CURVATURE_THRESHOLD: f64 = -0.5;

// ============================================================================
// SINKHORN TRANSPORT PARAMETERS
// ============================================================================

/// Maximum number of Sinkhorn-Knopp iterations before declaring non-convergence.
///
/// `NonZeroUsize` guarantees that the iteration budget is always meaningful
/// and that downstream code can safely use this value as a loop bound or
/// divisor without a zero-check.
///
/// Access the raw value with `.get()`.
///
/// AX-ID: AXIOMA-015, `ENGINEERING_BLUEPRINT` §4.1
// SAFETY: 1_000 is a non-zero literal. NonZeroUsize::new(1_000).unwrap() is the const-safe
// equivalent but Option::unwrap() is not yet stable as a const fn on our MSRV (Rust 1.75).
// When MSRV >= 1.83, replace with: NonZeroUsize::new(1_000).unwrap()
// SAFETY: 1_000 is non-zero; new_unchecked avoids const-unstable Option::unwrap on MSRV 1.75.
#[allow(clippy::useless_nonzero_new_unchecked)]
pub const SINKHORN_MAX_ITER: NonZeroUsize = unsafe { NonZeroUsize::new_unchecked(1_000) };

/// L∞ residual threshold for Sinkhorn-Knopp convergence declaration.
///
/// Must satisfy: `SINKHORN_CONVERGENCE_EPSILON` ≤ `FISHER_SATIATION_EPSILON`.
/// Current: 1e-9 ≤ 1e-6 ✓
///
/// AX-ID: AXIOMA-015, `ENGINEERING_BLUEPRINT` §4.1
pub const SINKHORN_CONVERGENCE_EPSILON: f64 = 1e-9;

/// Entropic regularisation parameter λ for Sinkhorn transport.
///
/// AX-ID: AXIOMA-015
pub const SINKHORN_REGULARISATION: f64 = 5e-2;

// ============================================================================
// JOHNSON-LINDENSTRAUSS BASIS Expansion
// ============================================================================

/// Residual magnitude threshold for Johnson-Lindenstrauss basis expansion.
///
/// **Invariant:** Must be strictly greater than `COGNITIVE_PLANCK_CONSTANT`
/// to avoid expanding the basis for thermal noise.
///
/// AX-ID: AXIOMA-014, `ENGINEERING_BLUEPRINT` §4.4
pub const JL_RESIDUAL_EXPANSION_DELTA: f64 = 1e-3;

// ============================================================================
// HEAT EQUATION PRUNING
// ============================================================================

/// Convergence threshold for the heat equation pruner ∂_t u = `Δ_g` u.
///
/// Must satisfy: `COGNITIVE_PLANCK_CONSTANT` < `HEAT_DIFFUSION_CONVERGENCE_EPSILON`
///               < `FISHER_SATIATION_EPSILON`
/// Current: 1e-12 < 1e-8 < 1e-6 ✓
///
/// AX-ID: AXIOMA-016, `IMPLEMENTATION_ROADMAP` §4.4
pub const HEAT_DIFFUSION_CONVERGENCE_EPSILON: f64 = 1e-8;

// ============================================================================
// COMPILE-TIME SIZE INVARIANTS (static_assertions)
// ============================================================================
//
// f64 ordering is not a `const` operation in stable Rust; the ordering
// invariants among the physical constants are verified in the test suite below.
// Integer and struct-size invariants are verified here at compile time.

static_assertions::const_assert_eq!(CLIFFORD_BASIS_SIZE, 1 << MAX_CLIFFORD_GRADE);
static_assertions::const_assert!(CLIFFORD_BASIS_SIZE > 0);
static_assertions::const_assert!(MAX_CLIFFORD_GRADE > 0);

/// Validates cross-constant floating-point ordering invariants at runtime.
///
/// This guard complements compile-time integer assertions; stable Rust cannot
/// encode floating-point relational const-assertions on MSRV 1.75.
///
/// AX-ID: AXIOMA-001, AXIOMA-008, AXIOMA-014, AXIOMA-015, AXIOMA-016
#[inline]
pub const fn validate_constant_ordering() -> bool {
    COGNITIVE_PLANCK_CONSTANT < HEAT_DIFFUSION_CONVERGENCE_EPSILON
        && HEAT_DIFFUSION_CONVERGENCE_EPSILON < FISHER_SATIATION_EPSILON
        && JL_RESIDUAL_EXPANSION_DELTA > COGNITIVE_PLANCK_CONSTANT
        && SINKHORN_CONVERGENCE_EPSILON <= FISHER_SATIATION_EPSILON
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
#[allow(clippy::assertions_on_constants)]
mod tests {
    use super::*;

    /// AX-ID: AXIOMA-001, AXIOMA-002
    #[test]
    fn minkowski_signature_time_positive() {
        assert!(MINKOWSKI_SIGNATURE[0] > 0.0);
    }

    /// AX-ID: AXIOMA-001, AXIOMA-002
    #[test]
    fn minkowski_signature_space_negative() {
        // CORRECTION-3: unrolled to avoid needless_range_loop over fixed array.
        assert!(MINKOWSKI_SIGNATURE[1] < 0.0);
        assert!(MINKOWSKI_SIGNATURE[2] < 0.0);
        assert!(MINKOWSKI_SIGNATURE[3] < 0.0);
    }

    #[test]
    fn minkowski_signature_exact_values() {
        assert_eq!(MINKOWSKI_SIGNATURE, [1.0, -1.0, -1.0, -1.0]);
    }

    #[test]
    fn cognitive_planck_constant_positive_and_small() {
        assert!(COGNITIVE_PLANCK_CONSTANT > 0.0);
        assert!(COGNITIVE_PLANCK_CONSTANT < 1e-6);
    }

    #[test]
    fn spatial_basis_mask_covers_bits_1_2_3_only() {
        // assert_eq!/assert_ne! with format strings are not constifiable.
        // The mask values are literals — runtime assertions are acceptable here.
        assert_eq!(
            SPATIAL_BASIS_MASK & 0b0001,
            0,
            "Bit 0 (time) must NOT be spatial"
        );
        assert_ne!(SPATIAL_BASIS_MASK & 0b0010, 0, "Bit 1 (e₁) must be spatial");
        assert_ne!(SPATIAL_BASIS_MASK & 0b0100, 0, "Bit 2 (e₂) must be spatial");
        assert_ne!(SPATIAL_BASIS_MASK & 0b1000, 0, "Bit 3 (e₃) must be spatial");
    }

    /// CORRECTION-3: use `.iter().enumerate()` to avoid needless_range_loop.
    #[test]
    fn spatial_mask_consistent_with_minkowski_signature() {
        for (i, &sig) in MINKOWSKI_SIGNATURE.iter().enumerate() {
            let bit_set = (SPATIAL_BASIS_MASK >> i) & 1 == 1;
            let is_spatial = sig < 0.0;
            assert_eq!(
                bit_set, is_spatial,
                "Bit {} of SPATIAL_BASIS_MASK inconsistent with MINKOWSKI_SIGNATURE[{}]={}",
                i, i, sig
            );
        }
    }

    #[test]
    fn soc_tau_range_biologically_valid() {
        assert!(SOC_TAU_MIN >= 1.5);
        assert!(SOC_TAU_MAX <= 2.5);
        assert!(SOC_TAU_MIN < SOC_TAU_MAX);
    }

    #[test]
    fn synchrony_threshold_in_unit_interval() {
        assert!(SYNCHRONY_COLLAPSE_THRESHOLD > 0.0);
        assert!(SYNCHRONY_COLLAPSE_THRESHOLD < 1.0);
    }

    // --- NonZeroUsize windows ---

    /// FISHER_SATIATION_WINDOW is NonZeroUsize — verify raw value via .get().
    ///
    /// AX-ID: AXIOMA-008
    #[test]
    fn fisher_satiation_window_nonzero_get() {
        assert_eq!(FISHER_SATIATION_WINDOW.get(), 50);
    }

    /// SINKHORN_MAX_ITER is NonZeroUsize — verify raw value via .get().
    ///
    /// AX-ID: AXIOMA-015
    #[test]
    fn sinkhorn_max_iter_nonzero_get() {
        assert_eq!(SINKHORN_MAX_ITER.get(), 1_000);
    }

    // --- Sinkhorn ---

    /// Transport convergence precision must be at least as fine as Fisher
    /// satiation resolution.
    ///
    /// AX-ID: AXIOMA-008, AXIOMA-015
    #[test]
    fn sinkhorn_convergence_at_most_equal_to_fisher_satiation() {
        assert!(SINKHORN_CONVERGENCE_EPSILON <= FISHER_SATIATION_EPSILON);
    }

    #[test]
    fn sinkhorn_regularisation_positive() {
        assert!(SINKHORN_REGULARISATION > 0.0);
    }

    // --- JL delta ---

    /// Basis expansion threshold must exceed the Planck thermal noise floor.
    ///
    /// AX-ID: AXIOMA-001, AXIOMA-014
    #[test]
    fn jl_residual_delta_above_planck_constant() {
        assert!(JL_RESIDUAL_EXPANSION_DELTA > COGNITIVE_PLANCK_CONSTANT);
    }

    // --- Ordering invariants ---

    /// Invariant chain: COGNITIVE_PLANCK_CONSTANT < HEAT_DIFFUSION_CONVERGENCE_EPSILON
    ///                                             < FISHER_SATIATION_EPSILON
    ///
    /// AX-ID: AXIOMA-016, `IMPLEMENTATION_ROADMAP` §4.4
    #[test]
    fn heat_diffusion_epsilon_between_planck_and_fisher() {
        assert!(HEAT_DIFFUSION_CONVERGENCE_EPSILON > COGNITIVE_PLANCK_CONSTANT);
        assert!(HEAT_DIFFUSION_CONVERGENCE_EPSILON < FISHER_SATIATION_EPSILON);
    }

    /// Full ordering chain for the audit's const_assert directives.
    ///
    /// AX-ID: AXIOMA-001, AXIOMA-008, AXIOMA-014, AXIOMA-015, AXIOMA-016
    #[test]
    fn constant_ordering_chain_is_consistent() {
        assert!(COGNITIVE_PLANCK_CONSTANT < HEAT_DIFFUSION_CONVERGENCE_EPSILON);
        assert!(HEAT_DIFFUSION_CONVERGENCE_EPSILON < FISHER_SATIATION_EPSILON);
        assert!(JL_RESIDUAL_EXPANSION_DELTA > COGNITIVE_PLANCK_CONSTANT);
        assert!(SINKHORN_CONVERGENCE_EPSILON <= FISHER_SATIATION_EPSILON);
        assert!(validate_constant_ordering());
    }
}

// ============================================================================
// PROOF SYSTEM PARAMETERS (GENESIS_PROOF_SPEC v1.1.0)
// ============================================================================

/// Minimum algebraic connectivity λ₂ of the HNSW graph.
/// If λ₂ < `LAMBDA2_MIN`, the system rejects the configuration.
///
/// AX-ID: `LEY_FUNDACIONAL` §5.3
pub const LAMBDA2_MIN: f64 = 0.1;

/// `H_restricción` penalty when a mutation lacks a valid Proof.
///
/// AX-ID: `LEY_FUNDACIONAL` §3.5
pub const PROOF_PENALTY: f64 = 1000.0;

/// Maximum time (nanoseconds) for which a Proof remains valid (anti-replay).
///
/// AX-ID: `GENESIS_PROOF_SPEC` §2.2
pub const PROOF_MAX_AGE_NS: u64 = 5_000_000_000;

// ============================================================================
// VARIATIONAL EXTENSIONS v1.1.0 (LEY_FUNDACIONAL §9)
// ============================================================================

/// Penalty for excessive edge density in `H_restricción`.
/// `κ_s` = 50.0 — penalizes |E| > N·log(N).
///
/// AX-ID: `LEY_FUNDACIONAL` §3.5
pub const DENSITY_PENALTY: f64 = 50.0;

/// Coupling factor for `H_dualidad`.
/// δ = 0.01 — penalizes divergence between g_{ij} and G^Fisher_{ij}.
///
/// AX-ID: `LEY_FUNDACIONAL` §3.6
pub const DELTA_DUALITY: f64 = 0.01;

/// Penalty for representational redundancy in `H_compresión`.
/// `κ_r` = 0.05
///
/// AX-ID: `LEY_FUNDACIONAL` §3.7
pub const KAPPA_REDUNDANCY: f64 = 0.05;

/// Search radius for redundancy detection in `H_compresión`.
/// `ε_r` = 0.1
///
/// AX-ID: `LEY_FUNDACIONAL` §3.7
pub const REDUNDANCY_RADIUS: f64 = 0.1;

/// Phase differentiation threshold for `H_compresión`.
/// `θ_r` = 0.3 — if ||φᵢ - φⱼ|| < `θ_r`, nodes are redundant.
///
/// AX-ID: `LEY_FUNDACIONAL` §3.7
pub const PHASE_DISTINCTION_THRESHOLD: f64 = 0.3;

/// Fixed existence cost of a new dimension.
/// `λ_fixed` = 0.05
///
/// AX-ID: `LEY_FUNDACIONAL` §3.8, §5.7
pub const LAMBDA_DIM_FIXED: f64 = 0.05;

/// Logarithmic scale cost of a new dimension.
/// `λ_log` = 0.01 — the cost grows with ln(N).
///
/// AX-ID: `LEY_FUNDACIONAL` §3.8, §5.7
pub const LAMBDA_DIM_LOG: f64 = 0.01;

// ── Kuramoto Adaptive Coupling — Frustration + Semantic Habituation ───────────

/// Isotropic coupling baseline α in the adaptive Kuramoto formula.
///
/// `base_Γ = Γ₀ · (Aᵢ · Aⱼ / Ā²) · (α + β · ⟨Bᵢ, Bⱼ⟩₂)`
///
/// With β=0, reduces to amplitude-weighted classical Kuramoto.
///
/// AX-ID: AXIOMA-006, H_dinámica (LEY_FUNDACIONAL §3.2)
pub const KURAMOTO_COUPLING_ALPHA: f64 = 1.0;

/// Bivector frustration weight β in the adaptive Kuramoto coupling.
///
/// Scales the geometric frustration term `⟨Bᵢ, Bⱼ⟩₂` (bivector inner product).
/// Positive β → anti-aligned bivectors produce negative (repulsive) coupling.
/// This prevents global synchronisation by respecting semantic orientation.
///
/// Range: `α + β · dot_biv ∈ (α − β|max|, α + β|max|)`.
/// With β = 0.5 and normalised bivectors: coupling ∈ (0.5, 1.5).
///
/// AX-ID: AXIOMA-006, H_dinámica (LEY_FUNDACIONAL §3.2)
pub const KURAMOTO_COUPLING_BETA: f64 = 0.5;

/// Minimum adaptive coupling after frustration and habituation.
///
/// Prevents total coupling suppression between active high-uncertainty pairs.
/// `adaptive_Γ.max(KURAMOTO_COUPLING_FLOOR)` before applying to step.
///
/// AX-ID: AXIOMA-006
pub const KURAMOTO_COUPLING_FLOOR: f64 = 0.0;

// ── Kuramoto Phase Transition — Wolfram Analytics (STEP 1) ───────────────────
//
// These constants are derived analytically from the Lorentzian frequency
// distribution on an HNSW graph with mean degree K=16.
//
// Derivation: Γ_c = 2γ / λ_max where:
//   γ = Lorentzian half-width (natural frequency spread)
//   λ_max = largest eigenvalue of the HNSW Laplacian at K=16
//
// AX-ID: AXIOMA-006, H_dinámica (LEY_FUNDACIONAL §3.2)

/// Half-width of the Lorentzian distribution of natural frequencies.
///
/// Controls the thermal noise floor: oscillators with |ω_i - ω_j| >> γ
/// do not synchronise regardless of coupling strength.
///
/// Wolfram derivation: γ = 0.1 for normalised HNSW Laplacian at K=16.
/// AX-ID: AXIOMA-006
pub const KURAMOTO_GAMMA_WIDTH: f64 = 0.1;

/// Expected maximum eigenvalue of the HNSW layer-0 Laplacian at mean degree K=16.
///
/// λ_max ≈ K = 16.0 for a K-regular random graph (Perron-Frobenius bound).
/// Used to derive `KURAMOTO_CRITICAL_COUPLING`.
///
/// AX-ID: AXIOMA-006
pub const KURAMOTO_LAMBDA_MAX_EXPECTED: f64 = 20.0;

/// Critical coupling threshold for Cognitive Ignition: Γ_c = 2γ / λ_max.
///
/// Below this value: phases are disordered (thermal noise dominates).
/// Above this value: synchronisation emerges and structured thought forms.
///
/// Wolfram derivation: Γ_c = 2 × 0.1 / 20.0 = 0.01
///
/// AX-ID: AXIOMA-006, AXIOMA-005 (SOC — system operates near this threshold)
pub const KURAMOTO_CRITICAL_COUPLING: f64 =
    (2.0 * KURAMOTO_GAMMA_WIDTH) / KURAMOTO_LAMBDA_MAX_EXPECTED;

/// Strong-coupling regime where r_sync → 1 (phase collapse imminent).
///
/// When Γ >> Γ_c, the system locks and a Lindblad collapse event is likely.
/// Used by `criticality.rs` to detect pre-collapse states.
///
/// AX-ID: AXIOMA-006
pub const KURAMOTO_STRONG_COUPLING: f64 = 0.35;

// ── Ricci Flow Logarithmic Parametrisation (CRATE-004) ───────────────────────

/// Edge weight below which `WormholeCollapse::CollapseReason::Ricci` fires.
///
/// Ricci flow operates on `l_ij = ln(w_ij)`. When `w_ij = exp(l_ij)` falls
/// below this threshold, inelastic fusion is triggered instead of further
/// diffusion — preventing geometrically degenerate edges.
///
/// The log-parametrisation guarantees w_ij > 0 at all times (no negative weights).
/// This threshold replaces the former `WORMHOLE_CURVATURE_THRESHOLD` as the
/// primary collapse criterion for the Ricci path.
///
/// AX-ID: AXIOMA-015, H_estructura (LEY_FUNDACIONAL §3.1)
pub const RICCI_PREEMPTIVE_THRESHOLD: f64 = 1e-4;

// ── Micro-Sinkhorn L1 Cache Parameters (CRATE-004) ───────────────────────────

/// Maximum number of neighbours considered per node in micro-Sinkhorn transport.
///
/// Micro-Sinkhorn computes optimal transport on the local HNSW neighbourhood,
/// not globally. This bounds the cost matrix size: `MAX_LOCAL_DEGREE² × f32`.
/// With `MAX_LOCAL_DEGREE = 32`, cost matrix = 32×32×4 = 4096 bytes — fits L1.
///
/// Must be ≥ `M0` in genesis-topology (currently 32). Increasing beyond 64
/// pushes the cost matrix to 16KB, near L1 boundary — verify before changing.
///
/// AX-ID: AXIOMA-015, LEY_FUNDACIONAL §3.1
pub const SINKHORN_MAX_LOCAL_DEGREE: usize = 32;

/// Log-domain Sinkhorn regularisation ε for micro-Sinkhorn L1.
///
/// Controls sharpness of optimal transport solution. Larger ε = more diffuse
/// (faster convergence, less accurate W₁). Smaller ε = sharper (more accurate
/// W₁, risk of numerical underflow in primal domain).
///
/// Log-domain implementation avoids underflow: `exp(-C/ε)` never computed.
/// All operations in log-space via `LogSumExp(x) = max(x) + ln(Σ exp(xᵢ - max))`.
///
/// AX-ID: AXIOMA-015
pub const SINKHORN_LOG_EPSILON: f32 = 5e-2_f32;

/// Maximum iterations for micro-Sinkhorn L1 convergence.
///
/// 12–15 iterations suffice for ε = 5e-2 on 32×32 cost matrices.
/// Stateless — no heap allocation per iteration.
///
/// AX-ID: AXIOMA-015
pub const SINKHORN_L1_MAX_ITER: usize = 15;
